services:
    postgres:
        image: postgres:16
        container_name: finance-app-postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: root
            POSTGRES_DB: finance-app
        ports:
            - '5432:5432'
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data

    postgres-test:
        image: postgres:16
        container_name: finance-app-postgres-test
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: root
            POSTGRES_DB: finance-app-test
        ports:
            - '5433:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U root -d finance-app-test']
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        container_name: finance-app-redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data

volumes:
    redis-data:
        driver: local
