version: '3'

services:
    postgres:
        image: postgres:15
        container_name: finance-app-postgres
        restart: unless-stopped           # reinicia em caso de falha
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_USER: root
            POSTGRES_DB: finance-app
        ports:
            - '5432:5432' 
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data

