# ### USERS

# Create User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "first_name": "aaaa",
  "last_name": "aaaaa", 
  "email": "kaue@gmail.com",
  "password": "password123"
}

###


# Login User
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "kaue@gmail.com",
  "password": "password123"
}

###

# Get User By Id
GET http://localhost:3001/api/users/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMDE5YTVkNC1jNTc0LTQyMzYtODBjYS0wYWEzNTQwYzYwMWYiLCJpYXQiOjE3NTY3MzUzNTgsImV4cCI6MTc1NjczNjI1OH0.tdVwPpEcPcUintdvmmB_S_IUr9-Nx1e-gLHzJkIZIpA

###

# Get User Balance
GET http://localhost:3001/api/users/me/balance
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMDE5YTVkNC1jNTc0LTQyMzYtODBjYS0wYWEzNTQwYzYwMWYiLCJpYXQiOjE3NTY3MzUzNTgsImV4cCI6MTc1NjczNjI1OH0.tdVwPpEcPcUintdvmmB_S_IUr9-Nx1e-gLHzJkIZIpA

###

# Update User
PATCH http://localhost:3001/api/users/me
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMDE5YTVkNC1jNTc0LTQyMzYtODBjYS0wYWEzNTQwYzYwMWYiLCJpYXQiOjE3NTY3MzUzNTgsImV4cCI6MTc1NjczNjI1OH0.tdVwPpEcPcUintdvmmB_S_IUr9-Nx1e-gLHzJkIZIpA

{
  "first_name": "piton",
  "last_name": "delas",
  "email": "kaua@gmail.com",
  "password": "newpassword456"
}

###

# Delete User
DELETE http://localhost:3001/api/users/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiOTk5MDljZC03ZDRmLTQ3NzgtYTAyMi0zYWRjMjBkNGQ2MjIiLCJpYXQiOjE3NTY3MzU1MDcsImV4cCI6MTc1NjczNjQwN30.v3Ihp8QDtchaUyG3Kn7mk91RLoreQlxcucm7DK1kVwY

###

# Refresh Token
POST http://localhost:3001/api/users/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDljYWE1Yi0wY2RmLTQ0NTktOGQ4MS1lYmFhNjI5M2QyYWMiLCJpYXQiOjE3NTY4MTg3NDQsImV4cCI6MTc1NzQyMzU0NH0.2lP9Y-NpA5CqxI0R8Ov14b2-C20KTomOu1AFPx1c3zg"
}

###

---

### TRANSACTIONS

# Create Transaction
POST http://localhost:3001/api/transactions/me
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDljYWE1Yi0wY2RmLTQ0NTktOGQ4MS1lYmFhNjI5M2QyYWMiLCJpYXQiOjE3NTY3NjQ3ODUsImV4cCI6MTc1Njc2NTY4NX0.GDIByKCCm3DcIvO08l4YB6mh6B9TrYdSE_kvcOVr5Dk

{
  "name": "pizza",
  "amount": 5000,
  "date": "2024-06-01T00:00:00.000Z",
  "type": "EARNING"
}

###

# Get Transactions By User Id
GET http://localhost:3001/api/transactions/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDljYWE1Yi0wY2RmLTQ0NTktOGQ4MS1lYmFhNjI5M2QyYWMiLCJpYXQiOjE3NTY3NjQ3ODUsImV4cCI6MTc1Njc2NTY4NX0.GDIByKCCm3DcIvO08l4YB6mh6B9TrYdSE_kvcOVr5Dk


###

# Update Transaction
PATCH http://localhost:3001/api/transactions/8dcc9a8b-b4cc-4d6b-80fc-d2fbd1a4dd3b
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDljYWE1Yi0wY2RmLTQ0NTktOGQ4MS1lYmFhNjI5M2QyYWMiLCJpYXQiOjE3NTY3NjQ3ODUsImV4cCI6MTc1Njc2NTY4NX0.GDIByKCCm3DcIvO08l4YB6mh6B9TrYdSE_kvcOVr5Dk

{
  "amount": 126000,
  "date": "2025-08-02T00:00:00.000Z",
  "type": "EXPENSE"
}

###

# Delete Transaction
DELETE http://localhost:3001/api/transactions/8dcc9a8b-b4cc-4d6b-80fc-d2fbd1a4dd3b
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDljYWE1Yi0wY2RmLTQ0NTktOGQ4MS1lYmFhNjI5M2QyYWMiLCJpYXQiOjE3NTY3NjQ3ODUsImV4cCI6MTc1Njc2NTY4NX0.GDIByKCCm3DcIvO08l4YB6mh6B9TrYdSE_kvcOVr5Dk
