# ### USERS

# Create User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "firstName": "aaaa",
  "lastName": "aaaaa", 
  "email": "iaq@gmail.com",
  "password": "password123"
}

###


# Login User
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "iaq@gmail.com",
  "password": "password123"
}

###

# Get User By Id
GET http://localhost:3001/api/users/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTc2Mjg5NzIsImV4cCI6MTc1NzYyOTg3Mn0.Oar79tOs1wnmkbfX0ml0KUJgRsFXJyI5JeH3iAg4V1k

###

# Get User Balance
GET http://localhost:3001/api/users/me/balance
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMDE5YTVkNC1jNTc0LTQyMzYtODBjYS0wYWEzNTQwYzYwMWYiLCJpYXQiOjE3NTY3MzUzNTgsImV4cCI6MTc1NjczNjI1OH0.tdVwPpEcPcUintdvmmB_S_IUr9-Nx1e-gLHzJkIZIpA

###

# Update User
PATCH http://localhost:3001/api/users/me
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMDE5YTVkNC1jNTc0LTQyMzYtODBjYS0wYWEzNTQwYzYwMWYiLCJpYXQiOjE3NTY3MzUzNTgsImV4cCI6MTc1NjczNjI1OH0.tdVwPpEcPcUintdvmmB_S_IUr9-Nx1e-gLHzJkIZIpA

{
  "firstName": "piton",
  "lastName": "delas",
  "email": "kaua@gmail.com",
  "password": "newpassword456"
}

###

# Delete User
DELETE http://localhost:3001/api/users/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiOTk5MDljZC03ZDRmLTQ3NzgtYTAyMi0zYWRjMjBkNGQ2MjIiLCJpYXQiOjE3NTY3MzU1MDcsImV4cCI6MTc1NjczNjQwN30.v3Ihp8QDtchaUyG3Kn7mk91RLoreQlxcucm7DK1kVwY

###

# Refresh Token
POST http://localhost:3001/api/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTc1NTIxODMsImV4cCI6MTc1ODE1Njk4M30.QNQBLoqZ_aEon5rQn9sPNrMhtwApAVne4rvRblCbYzo"
}

###





### TRANSACTIONS

# Create Transaction
POST http://localhost:3001/api/transactions/me
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTc2MzAxNTUsImV4cCI6MTc1NzYzMTA1NX0._cRkIRUFoeJKB42wm2sUraTazDTKR_gYIxxF1IyDzxI

{
  "name": "pizza",
  "amount": 5000,
  "date": "2025-08-08T00:00:00.000Z",
  "type": "EARNING"
}

###

# Get Transactions By User Id
GET http://localhost:3001/api/transactions/me?from=2025-08-01&to=2025-08-08
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTc2Mjg5NzIsImV4cCI6MTc1NzYyOTg3Mn0.Oar79tOs1wnmkbfX0ml0KUJgRsFXJyI5JeH3iAg4V1k


###

# Update Transaction
PATCH http://localhost:3001/api/transactions/me/213c5188-3067-4974-af6b-7c62bed0a8fc
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTc2Mjg5NzIsImV4cCI6MTc1NzYyOTg3Mn0.Oar79tOs1wnmkbfX0ml0KUJgRsFXJyI5JeH3iAg4a1k

{
  "amount": 126000,
  "date": "2025-08-02T00:00:00.000Z",
  "type": "EXPENSE"
}

###

# Delete Transaction
DELETE http://localhost:3001/api/transactions/me/213c5188-3067-4974-af6b-7c62bed0a8fc
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTc2Mjg5NzIsImV4cCI6MTc1NzYyOTg3Mn0.Oar79tOs1wnmkbfX0ml0KUJgRsFXJyI5JeH3iAg4V1k
