export enum ErrorCode {
    // User
    USER_INVALID_CREDENTIALS = 'USER_INVALID_CREDENTIALS',
    USER_INVALID_FIRST_NAME = 'USER_INVALID_FIRST_NAME',
    USER_INVALID_LAST_NAME = 'USER_INVALID_LAST_NAME',
    USER_INVALID_NAME = 'USER_INVALID_NAME',
    USER_INVALID_EMAIL = 'USER_INVALID_EMAIL',
    USER_ID_MISSING = 'USER_ID_MISSING',
    USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    INVALID_PASSWORD = 'INVALID_PASSWORD',

    // Transaction
    TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
    TRANSACTION_UPDATE_FAILED = 'TRANSACTION_UPDATE_FAILED',
    TRANSACTION_DELETE_FAILED = 'TRANSACTION_DELETE_FAILED',

    // Common
    FORBIDDEN = 'FORBIDDEN',
    INVALID_ID = 'INVALID_ID',
    MISSING_FIELD = 'MISSING_FIELD',
    BAD_REQUEST = 'BAD_REQUEST',
}
