# ### USERS

# Create User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "firstName": "aaaa",
  "lastName": "aaaaa", 
  "email": "iaq@gmail.com",
  "password": "password123"
}

###


# Login User
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "iaq@gmail.com",
  "password": "password123"
}

###

# Get User By Id
GET http://localhost:3001/api/users/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTc2Mzk4MjAsImV4cCI6MTc1NzY0MDcyMH0.yZ4eGZERzw7tbfKTGtdAVMl5lXLwq2cZnSfrHYu2bqo

###

# Get User Balance
GET http://localhost:3001/api/users/me/balance?from=2025-08-01&to=2025-09-18
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YTZlYjIyYi0wMjcwLTRjNDMtYmVmMi1jZjllZDFkOWIyYjEiLCJpYXQiOjE3NTgwNjc2NzIsImV4cCI6MTc1ODA2ODU3Mn0.z19GLNMY8ddYZBu0uiPL6xUw4qrc9hTd1JtUusnid9U

###

# Update User
PATCH http://localhost:3001/api/users/me
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTc2Mzk4MjAsImV4cCI6MTc1NzY0MDcyMH0.yZ4eGZERzw7tbfKTGtdAVMl5lXLwq2cZnSfrHYu2bqo

{
  "firstName": "piton",
  "lastName": "delas",
  "email": "kaua@gmail.com",
  "password": "newpassword456"
}

###

# Delete User
DELETE http://localhost:3001/api/users/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiOTk5MDljZC03ZDRmLTQ3NzgtYTAyMi0zYWRjMjBkNGQ2MjIiLCJpYXQiOjE3NTY3MzU1MDcsImV4cCI6MTc1NjczNjQwN30.v3Ihp8QDtchaUyG3Kn7mk91RLoreQlxcucm7DK1kVwY

###

# Refresh Token
POST http://localhost:3001/api/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTc1NTIxODMsImV4cCI6MTc1ODE1Njk4M30.QNQBLoqZ_aEon5rQn9sPNrMhtwApAVne4rvRblCbYzo"
}

###





### TRANSACTIONS

# Create Transaction
POST http://localhost:3001/api/transactions/me
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YTZlYjIyYi0wMjcwLTRjNDMtYmVmMi1jZjllZDFkOWIyYjEiLCJpYXQiOjE3NTgwNjg1MDEsImV4cCI6MTc1ODA2OTQwMX0.Ms-ZDi-ya0QYAeSHLwrEm_bn--z0NtiE0zuLRPsb24E

{
  "name": "supermercado",
  "amount": 5000,
  "date": "2025-08-08T00:00:00.000Z",
  "type": "EXPENSE"
}

###

# Get Transactions By User Id
# &type=EXPENSE &minAmount=50 &name=supermercado&
GET http://localhost:3001/api/transactions/me?from=2025-01-01&to=2025-12-31&limit=2&cursor=
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YTZlYjIyYi0wMjcwLTRjNDMtYmVmMi1jZjllZDFkOWIyYjEiLCJpYXQiOjE3NTgwNjg1MDEsImV4cCI6MTc1ODA2OTQwMX0.Ms-ZDi-ya0QYAeSHLwrEm_bn--z0NtiE0zuLRPsb24E


###

# Update Transaction
PATCH http://localhost:3001/api/transactions/me/ed69064c-b69f-4aba-bba6-dfb3765127ac
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTc2Mzk4OTYsImV4cCI6MTc1NzY0MDc5Nn0.qgVMxMO8XuQoToji33lpBTwIhPlSIeokhawJrmkIR7U

{
  "amount": 126000,
  "date": "2025-08-02T00:00:00.000Z",
  "type": "EXPENSE"
}

###

# Delete Transaction
DELETE http://localhost:3001/api/transactions/me/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYjQ4ODI2Yi05ZDcxLTRiMTgtOGUxNi03YzZiN2NhZDQzNjIiLCJpYXQiOjE3NTgwNjI2MDMsImV4cCI6MTc1ODA2MzUwM30.meueRe3tgTCFZQAGQl_3mfV8qi__1rfvbqKF56t6Kes
